#!/bin/bash
set -o errexit -o nounset -o pipefail

transport=${DIAMANEOS_PUBLICATION_TRANSPORT:?Set the publication transport executable}
if [[ $transport != /* || ! -f $transport || ! -x $transport || ! -O $transport || -L $transport ]] ||
        [[ -n $(find "$transport" \( -perm -020 -o -perm -002 \) -print) ]]; then
    echo 'Publication transport must be an absolute, protected executable.' >&2
    exit 2
fi

touch lock
exec {fd}< lock
if ! flock -n "$fd"; then
    echo 'Application catalog is locked.' >&2
    exit 1
fi

./process-static "$fd"
"$transport" apps-publish "$PWD/static-tmp"
